### ISSUE TITLE
rosrun dl_node dl_node_sptam.py

### ISSUE THREAD

**Issue by liucsg** [CIFASIS/object-detection-sptam#1]
Hi, I cannot run "rosrun dl_node dl_node_sptam.py". There is no model exists, such as roomgen15k_voc_120000.caffemodel!

**Comment by eevidal** [comment]
Hello, 
Well we do not provide a file named `roomgen15k_voc_120000.caffemodel,` you can use  `pose_coco_Allconst_iter16000.caffemodel,` instead. It is new (you must run `git lfs pull` ). Then you will need to set the variable "caffemodel" with the correct path. 
Anyway that way of launching the node is not tested by us at the moment. Did you already try the launch? 
`roslaunch sptam dl_zed.launch` 

Regards

**Comment by liucsg** [comment]
all right！ I have successfully tried to run the launch 
      **roslaunch sptam dl_zed.launch** 
Could you tell me how to run the complete project and  get visualization ?

**Comment by liucsg** [comment]
Also, I cannot run this command because i have no account of “git@repositorio.cifasis-conicet.gov.ar”
**git submodule update --init --recursive**

**Comment by eevidal** [comment]
About the submodule, yes it is private for now. But I added a new copy of sptam which is exactly as the submodule you need to run the node, but not for the visualization. Sorry about the mess, we are cleaning the code right now, but it will take some time (a couple of days, maybe).

**Comment by liucsg** [comment]
Thank you!
There's another problem in the directory of plotters. Because,the comparisonPlotter file does not exist.
   **import comparisonPlotter as comparador**
