### ISSUE TITLE
git lfs pull

### ISSUE THREAD

**Issue by liucsg** [CIFASIS/object-detection-sptam#2]
Hi , I have a prolem when running 'git lfs pull'
**batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
error: failed to fetch some objects from 'https://github.com/CIFASIS/object-detection-sptam.git/info/lfs'**

**Comment by liucsg** [comment]
Hi, could you put the model in another place ?

**Comment by eevidal** [comment]
Hello, 
You can download the model from https://www.cifasis-conicet.gov.ar/~erica/caffeModels/

cheers

**Comment by liucsg** [comment]
Thank you very much!
